services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.websecure.address=:443
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  analyzer:
    build: ./analyzer
    image: presidio-analyzer-sv:latest
    container_name: presidio-analyzer-sv
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.analyzer.rule=Host(`${DOMAIN}`) && PathPrefix(`/analyzer`)"
      - traefik.http.routers.analyzer.entrypoints=websecure
      - traefik.http.routers.analyzer.tls.certresolver=letsencrypt
      - traefik.http.routers.analyzer.middlewares=analyzer-stripprefix
      - traefik.http.middlewares.analyzer-stripprefix.stripprefix.prefixes=/analyzer
      - traefik.http.services.analyzer.loadbalancer.server.port=80

  anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.anonymizer.rule=Host(`${DOMAIN}`) && PathPrefix(`/anonymizer`)"
      - traefik.http.routers.anonymizer.entrypoints=websecure
      - traefik.http.routers.anonymizer.tls.certresolver=letsencrypt
      - traefik.http.routers.anonymizer.middlewares=anonymizer-stripprefix
      - traefik.http.middlewares.anonymizer-stripprefix.stripprefix.prefixes=/anonymizer
      - traefik.http.services.anonymizer.loadbalancer.server.port=80
