services:
  analyzer:
    build: ./analyzer
    image: presidio-analyzer-sv:latest
    container_name: presidio-analyzer-sv
    ports:
      - "5002:3000"
    restart: unless-stopped

  anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    ports:
      - "5001:3000"
    restart: unless-stopped
