services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.analyzer.address=:5002
      - --entrypoints.anonymizer.address=:5001
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "8080:8080"
      - "5002:5002"
      - "5001:5001"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  analyzer:
    build: ./analyzer
    image: presidio-analyzer-sv:latest
    container_name: presidio-analyzer-sv
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.analyzer.rule=Host(`${DOMAIN}`)"
      - traefik.http.routers.analyzer.entrypoints=analyzer
      - traefik.http.routers.analyzer.tls=true
      - traefik.http.routers.analyzer.tls.certresolver=letsencrypt
      - traefik.http.services.analyzer.loadbalancer.server.port=3000

  anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.anonymizer.rule=Host(`${DOMAIN}`)"
      - traefik.http.routers.anonymizer.entrypoints=anonymizer
      - traefik.http.routers.anonymizer.tls=true
      - traefik.http.routers.anonymizer.tls.certresolver=letsencrypt
      - traefik.http.services.anonymizer.loadbalancer.server.port=3000
